BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE SCHEMA IF NOT EXISTS seguridad_vial;
SET search_path TO seguridad_vial, public;

CREATE TYPE estado_registro AS ENUM ('ACTIVO', 'INACTIVO');
CREATE TYPE tipo_plantel AS ENUM ('TITULAR', 'REEMPLAZANTE');
CREATE TYPE turno_codigo AS ENUM ('M', 'T', 'N');
CREATE TYPE tipo_posicion AS ENUM ('GENERAL', 'MOVIL4', 'VINCULADA');
CREATE TYPE tipo_configuracion AS ENUM ('GENERAL', 'FIJO_MOVIL', 'ROTACION_ESPECIAL');
CREATE TYPE tipo_capa AS ENUM ('BASE', 'PLANIFICADA', 'REAL');
CREATE TYPE estado_version AS ENUM (
    'BORRADOR',
    'EN_REVISION',
    'OBSERVADA',
    'APROBADA_PUBLICADA',
    'CERRADA',
    'REEMPLAZADA'
);
CREATE TYPE tipo_bloque AS ENUM ('TRABAJO', 'FRANCO');
CREATE TYPE origen_registro AS ENUM ('IMPORTADO', 'GENERADO', 'MANUAL', 'NOVEDAD', 'REAL');
CREATE TYPE tipo_dia AS ENUM ('TRABAJO', 'FRANCO', 'VACACION', 'LICENCIA', 'ENFERMEDAD', 'HUECO');
CREATE TYPE tipo_novedad AS ENUM ('VACACION', 'LICENCIA', 'ENFERMEDAD');
CREATE TYPE estado_novedad AS ENUM ('BORRADOR', 'APROBADA', 'CANCELADA', 'CERRADA');
CREATE TYPE tipo_ajuste_plan AS ENUM (
    'APLICAR_NOVEDAD',
    'TRABAJO_DEMANDA',
    'FRANCO_ADICIONAL',
    'REEMPLAZO',
    'CAMBIO_MANUAL',
    'HUECO_ACEPTADO'
);
CREATE TYPE tipo_evento_real AS ENUM (
    'CONFIRMACION_PLAN',
    'AUSENCIA',
    'REEMPLAZO',
    'CAMBIO_MOVIL',
    'CAMBIO_TURNO',
    'HUECO',
    'CORRECCION'
);
CREATE TYPE estado_cobertura AS ENUM ('HUECO', 'CUBIERTA', 'REFORZADA');
CREATE TYPE estado_inicializacion AS ENUM ('CARGADA', 'VALIDADA', 'CONFIRMADA', 'FALLIDA', 'REVERTIDA');
CREATE TYPE rol_posicion_vinculada AS ENUM ('MOVIL4', 'MOVIL_EXTERNO');
CREATE TYPE origen_ancla AS ENUM ('HISTORICO_EXCEL', 'CONFIGURACION');
CREATE TYPE estado_materializacion AS ENUM ('INICIADA', 'COMPLETADA', 'FALLIDA');

COMMIT;
